config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'
  get 'likes/destroy'
  get 'sessions/new'
  root 'main_page#main'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/newpost', to: 'microposts#new'

  resources :users do
    member do
      get :following, :followers
    end
    resources :favorites, only: :index
  end

  resources :microposts, only: [:create, :destroy, :show] do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :testsessions, only: :create
  resources :likes, only: [:create, :destroy]
end

app/controllers/main_page_controller.rb
class MainPageController < ApplicationController
  def main
    if logged_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page]).search(params[:search])
      @comment = Comment.new
    end
  end
end

app/helpers/main_page_helper.rb
module MainPageHelper
end

app/views/main_page/main.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
    </aside>
    <div class="col-md-8">
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %> 
  <div class="center jumbotron background">
    <h1>Portgram</h1>
    <p>海での思い出をみんなと共有しよう</p>

    <%= link_to "今すぐ始める", signup_path, class:"btn btn-lg btn-primary" %>
    <%= link_to "ログイン", login_path, class:"btn btn-lg btn-primary" %>
    <%= link_to "かんたんログイン", testsessions_path, method: :post, class:"btn btn-lg btn-primary" %>
  </div>
<% end %>