config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'
  get 'likes/destroy'
  get 'sessions/new'
  root 'main_page#main'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/newpost', to: 'microposts#new'

  resources :users do
    member do
      get :following, :followers
    end
    resources :favorites, only: :index
  end

  resources :microposts, only: [:create, :destroy, :show] do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :testsessions, only: :create
  resources :likes, only: [:create, :destroy]
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :love_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader

  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 200 }
  validates :picture, presence: true
  validate :picture_size
  validates :rate, presence: true
  validates :address, presence: true, length: { maximum: 50 }
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def love(user)
    likes.create(user_id: user.id)
  end

  def unlove(user)
    likes.find_by(user_id: user.id).destroy
  end

  def love?(user)
    love_users.include?(user)
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(search)
    if search
      where(['content LIKE ?', "%#{search}%"])
    else
      all
    end
  end

  private
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "画像サイズを5MB以下にしてください")
      end
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "投稿しました"
      redirect_to root_url
    else
      @feed_items = []
      render 'new'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "投稿を削除しました"
    redirect_to root_url
  end

  def new
    @micropost = current_user.microposts.build if logged_in?
  end

  def show 
    @micropost = Micropost.find(params[:id])
    @comment = Comment.new
    @user = User.find_by(id: @micropost.user_id)
  end

  private
    def micropost_params
      params.require(:micropost).permit(:content, :picture, :rate, :address, :latitude, :longitude)
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>" data-micropost-id="<%= micropost.id %>">
  <% micropost_user = micropost.user %>
  <%= link_to image_tag(micropost_user.usericon.url, class: "usericon", :size => "45x45"), micropost.user %>
  <%= link_to micropost.user.name, micropost.user %>
  <span class="content">
    <%= micropost.content %>
    <%= link_to image_tag(micropost.picture.url), micropost %>
  </span>
  <span class="timestamp">
    <%= time_ago_in_words(micropost.created_at) %>前に投稿
    <%= link_to "投稿詳細を見る", micropost %>
    <% if current_user?(micropost.user) %>
      <%= link_to "削除", micropost, method: :delete, data: { confirm: "削除してもよろしいですか？" } %>
    <% end %>
  </span>
</li>

app/views/microposts/new.html.erb
<% provide(:title, '新規投稿') %>
<h1>新規投稿</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @micropost, local: true) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="field">
        <%= f.text_area :content, placeholder: "本文を入力" %>
        <%= f.text_field :address, placeholder: "住所を入力　例）神奈川県横浜市" %>
      </div>
      <div class="micropost_rate">
        <p>海水浴場の評価</p>
        <%= f.radio_button :rate, :"非常に悪い" %>
        <%= f.label :rate, "非常に悪い", value: :"非常に悪い" %>
        <%= f.radio_button :rate, :"悪い" %>
        <%= f.label :rate, "悪い", value: :"悪い" %>
        <%= f.radio_button :rate, :"普通", checked: true %>
        <%= f.label :rate, "普通", value: :"普通" %>
        <%= f.radio_button :rate, :"良い" %>
        <%= f.label :rate, "良い", value: :"良い" %>
        <%= f.radio_button :rate, :"非常に良い" %>
        <%= f.label :rate, "非常に良い", value: :"非常に良い" %>
      </div>
      <span class="picture">
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png,image/jpg' %>
      </span>
      <%= f.submit "投稿する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('5MB以下のファイルを選択してください');
    }
  });
</script>

app/views/microposts/show.html.erb
<div class="row">
  <div class="col-md-8">
    <li class="microposts" id="@micropost-<%= @micropost.id %>" data-@micropost-id="<%= @micropost.id %>">
      <%= link_to image_tag(@user.usericon.url, class: "usericon", :size => "50x50"), @micropost.user %>
      <%= link_to @micropost.user.name, @micropost.user %>

      <span class="content">
        <%= @micropost.content %>
        <span class="timestamp">
          <%= time_ago_in_words(@micropost.created_at) %>前に投稿
          <% if current_user?(@micropost.user) %>
            <%= link_to "削除", @micropost, method: :delete, data: { confirm: "削除してもよろしいですか？" } %>
          <% end %>
        </span>
        <%= image_tag @micropost.picture.url if @micropost.picture? %>
      </span>

      <script type="text/javascript">
        function initMap() {
          test = {lat: <%= @micropost.latitude %>, lng: <%= @micropost.longitude %>};
          map = new google.maps.Map(document.getElementById('map'), {
            zoom: 15,
            center: test
          });

          var transitLayer = new google.maps.TransitLayer();
          transitLayer.setMap(map);

          var contentString = '住所：<%= @micropost.address %>';
          var infowindow = new google.maps.InfoWindow({
            content: contentString
          });

          var marker = new google.maps.Marker({
            position:test,
            map: map,
            title: contentString
          });

          marker.addListener('click', function() {
            infowindow.open(map, marker);
          });
        }
      </script>

      <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['API_KEY'] %>&callback=initMap" async defer></script>

      <p id="notice"><%= notice %></p>

      <style type="text/css">
        #map { height: 400px;
          float:right;
          margin-left:auto;
          margin-right:auto;
          margin-bottom:10px;
          text-align:left;
          width: 92%;}
      </style>

      <div id="map"></div>

      <div class="bottom-info">
        <span class="like">
          <%= render "likes/like", micropost: @micropost %>

          <% if @micropost.favorited_by?(current_user) %>
            <p><%=link_to "お気に入り解除", micropost_favorites_path(@micropost.id), method: :delete %></p>
          <% else %>
            <p><%=link_to "お気に入りする", micropost_favorites_path(@micropost.id), method: :post %></p>
          <% end %>
        </span>

        <span class="rating">
          <p>海水浴場の評価：<%= @micropost.rate %></p>
        </span>
      </div>

      <div class="comment_index">
        <% @micropost.comments.each do |comment| %>
          <ul class="comments">
            <span class="comment_user">
              <% comment_user = comment.user %>
              <%= link_to image_tag(comment_user.usericon.url, class: "usericon", :size => "30x30"), comment.user %>
              <%= link_to comment.user.name, comment.user %>
            </span>
            <span class="content">
              <%= comment.content %>
            </span>
            <span class="comment_timestamp">
              <%= time_ago_in_words(comment.created_at) %>前に投稿
              <%= link_to "削除", [@micropost, comment], method: :delete,
              data: { confirm: "コメントを削除してもよろしいですか？" } if current_user?(comment.user) %>
            </span>
          </ul>
        <% end %>
      </div>

      <div class="comment_form">
        <%= form_for([@micropost, @comment]) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
            <div class="field">
              <%= f.text_area :content, placeholder: "コメントを入力" %>
            </div>
            <%= f.submit "投稿", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</li>