config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'
  get 'likes/destroy'
  get 'sessions/new'
  root 'main_page#main'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/newpost', to: 'microposts#new'

  resources :users do
    member do
      get :following, :followers
    end
    resources :favorites, only: :index
  end

  resources :microposts, only: [:create, :destroy, :show] do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :testsessions, only: :create
  resources :likes, only: [:create, :destroy]
end

app/views/layouts/_after_login.html.erb
<body id="after_login">
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>

app/views/layouts/_before_login.html.erb
<body id="before_login">
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>

app/views/layouts/_head.html.erb
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'custom', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= render 'layouts/shim' %>
</head>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Portgram", root_path, id: "logo" %>
    <nav>
    <% if logged_in? %>
      <ul class="nav navbar-nav navbar-center">
        <%= form_tag root_path, :method => 'get' do %>
          <%= text_field_tag :search, params[:search], placeholder: "投稿を検索" %>
          <%= submit_tag "検索", :name => nil, class: "btn btn-primary" %>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "投稿", newpost_path %></li>
        <li><%= link_to "お気に入り", user_favorites_url(current_user) %></li>
        <li><%= link_to "マイページ", current_user %></li>
        <li><%= link_to "ログアウト", logout_path, method: :delete %></li>    
      </ul>
    <% end %>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
  <% if logged_in? %>
    <%= render 'layouts/after_login' %>
  <% else %>
    <%= render 'layouts/before_login' %>
  <% end %>
</html>